version: '3'
services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:1.20.0
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    ports:
      - "8000:8000"
    # volumes:
        # - .docker/dbdata:/home/dynamodblocal/data/
    working_dir: /home/dynamodblocal
    networks:
      - lambda-local
networks:
  lambda-local:
    external: true
